dependencies:
  - nbserverproxy
  - nbgitpuller 
  - tornado=5.1.1
  - intake
  - conda-forge::altair
  - conda-forge::plotly
  - pyviz/label/dev::geoviews-core=1.6.2
  - pyviz/label/dev::holoviews=1.12.2
  - pyviz/label/dev::geoviews-core=1.6.2
  - pyviz/label/dev::hvplot=0.4.0
  - pyviz/label/dev::panel=0.5.1
  - pyviz::param=1.9.0
  - pyviz::pyviz_comms=0.7.2
  - pyviz::datashader  
  - bokeh::bokeh=1.1.0
  - pandas>=0.23.4
  - xarray
  - netcdf4
  - fastparquet
